package com.tradeagent.strategy.backtest;

/** Completed or still-open trade generated by a backtest execution. */
public record BacktestTrade(
        String entryDate,
        int entryIndex,
        String exitDate,
        int exitIndex,
        double entryPrice,
        double exitPrice,
        double returnPct,
        boolean isOpen) {
}
